- name: install jdk
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: 
    - openjdk-7-jre-headless 
    - openjdk-7-jdk
    - maven2
  register: install_jdk

- name: install visualvm if available
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - visualvm
  when: (ansible_lsb.id == "Debian" and ansible_lsb.major_release|int >= 8) or ansible_lsb.id == "Ubuntu"

- name: set java7 as default
  command: update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
  when: install_jdk.changed
  
- name: download leiningen
  get_url:  url=https://raw.github.com/technomancy/leiningen/{{leiningen_version}}/bin/lein 
            dest=/usr/local/bin/lein-{{leiningen_version}}
            mode=0755

- name: link to main version of leinigen
  file: dest=/usr/local/bin/lein
        src=/usr/local/bin/lein-{{leiningen_version}}
        state=link

- name: root may execute leiningen 
  lineinfile: line='export LEIN_ROOT=True'
              state=present
              dest=~root/.bashrc

